# 1. MODEL CONFIGURATION: Define the model to be benchmarked.
# -------------------------------------------------------------------
model:
  # Path to the model's .py file. Now points to the wrapper script.
  path: models/detector_wrapper.py
  # Name of the model class within the .py file. Now points to the wrapper class.
  class_name: AudioDeepfakeDetector
  # The checkpoint path remains the same as it's passed through the wrapper.
  checkpoint: models/Best_LA_model_for_DF.pth
  device: 'cuda:0'

  # These key-value pairs will be passed directly to the model's __init__ method.
  # This section now holds the configuration for the *raw* model that the wrapper uses.
  model_args:
    raw_model_path: models/baseline_model.py
    raw_model_class_name: Model
    raw_model_args: # Arguments for the raw model's __init__
      args: null
      model_device: 'cuda:7'


# 2. DATA CONFIGURATION: Specify which dataset(s) to evaluate on.
# -------------------------------------------------------------------
# !!! IMPORTANT: You must specify EITHER a single `manifest_path` OR a `group_name`, but not both.
# To use a single dataset, fill in `manifest_path` and leave `group_name` as null.
# To use a dataset group, fill in `group_name` and leave `manifest_path` as null.
data:
  # --- Option A: For a single dataset run ---
  # manifest_path: data/timittts/processed/manifest_timittts.csv # e.g., "data/for-original/processed/manifest_for-original.csv"
  # group_name: null

  # # --- Option B: For a group run ---
  group_name: all # e.g., "all"

  # # Path to the YAML file that defines your dataset groups.
  groups_config_path: benchmark/dataset_group.yaml

  # --- Data loader hyperparameters ---
  data_args:
    target_sample_rate: 16000
    target_length: 64000

# 3. EVALUATION SETTINGS: Control the output and runtime parameters.
# -------------------------------------------------------------------
evaluation_settings:
  # Directory where all results (scores, metrics, tables) will be saved.
  results_dir: results
  # Batch size for the dataloader.
  batch_size: 256
  # Optional: If you provide a path here, a LaTeX .tex file with a results
  # table will be generated automatically. Leave as null to disable.
  latex_output_path: results/examplar_table.tex # e.g., null
