# ===================================================================
#               Configuration for the Evaluation Script
# ===================================================================

# 1. MODEL CONFIGURATION: Define the model to be benchmarked.
# -------------------------------------------------------------------
model:
  # Path to the model's .py file.
  path: models/baseline_model.py
  # Name of the model class within the .py file.
  class_name: Model
  # Path to the pretrained model checkpoint (.pth or similar).
  checkpoint: models/Best_LA_model_for_DF.pth
  device: 'cuda:7'

  # These key-value pairs will be passed directly to the model's __init__ method.
  # This allows you to use the same loader for models with different initializations.
  # Example: if your model is `def __init__(self, num_layers, device, **kwargs):`
  model_args:
    args: null
    model_device: 'cuda:7'


# 2. DATA CONFIGURATION: Specify which dataset(s) to evaluate on.
# -------------------------------------------------------------------
# !!! IMPORTANT: You must specify EITHER a single `manifest_path` OR a `group_name`, but not both.
# To use a single dataset, fill in `manifest_path` and leave `group_name` as null.
# To use a dataset group, fill in `group_name` and leave `manifest_path` as null.
data:
  # --- Option A: For a single dataset run ---
  manifest_path: data/Codecfake/processed/manifest_Codecfake.csv # e.g., "data/manifests/asvspoof2019.csv"
  group_name: null

  # # --- Option B: For a group run ---
  # group_name: real_and_fake # e.g., "real_and_fake"

  # # Path to the YAML file that defines your dataset groups.
  # groups_config_path: benchmarks/hparams/dataset_groups.yaml


# 3. EVALUATION SETTINGS: Control the output and runtime parameters.
# -------------------------------------------------------------------
evaluation_settings:
  # Directory where all results (scores, metrics, tables) will be saved.
  results_dir: results
  # Batch size for the dataloader.
  batch_size: 16
  # Optional: If you provide a path here, a LaTeX .tex file with a results
  # table will be generated automatically. Leave as null to disable.
  latex_output_path: results/examplar_table.tex # e.g., null
